# Generated by Django 4.1.3 on 2022-11-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=30)),
                ('quantity_per_unit', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store.category')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store.category')),
            ],
        ),
    ]
