# Generated by Django 4.1.3 on 2022-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
