# Generated by Django 4.1.3 on 2022-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0005_feedback_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mark',
            field=models.CharField(choices=[('1', '1 - Bad'), ('2', '1 - Better'), ('3', '1 - Normal'), ('4', '1 - Not enough'), ('5', '1 - Good')], max_length=9),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='short_mark',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=9),
        ),
    ]
