# Generated by Django 4.1.3 on 2022-11-18 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0006_alter_feedback_mark_alter_feedback_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 18, 11, 22, 26, 697220)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mark',
            field=models.CharField(choices=[('1', '1 - Bad'), ('2', '2 - Better'), ('3', '3 - Normal'), ('4', '4 - Not enough'), ('5', '5 - Good')], max_length=9),
        ),
    ]
