# Generated by Django 4.1.3 on 2022-11-19 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0007_supplier_created_alter_feedback_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 19, 19, 39, 40, 147498)),
        ),
    ]
