# Generated by Django 4.1.3 on 2022-11-22 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0009_game_alter_supplier_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 22, 16, 20, 35, 851817)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 22, 16, 20, 35, 851817)),
        ),
    ]
