# Generated by Django 4.1.3 on 2022-11-23 07:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_store', '0011_alter_feedback_created_alter_feedback_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='written_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Written by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 23, 8, 56, 18, 736894)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 23, 8, 56, 18, 736894)),
        ),
    ]
