# Generated by Django 4.1.3 on 2022-11-26 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0013_alter_feedback_created_alter_supplier_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 26, 11, 14, 40, 196444)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 11, 26, 11, 14, 40, 194442)),
        ),
    ]
